name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, mysql, zip

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 📂 Sync files via FTP
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USER }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: "./"
          dist_target_dir: "public_html/drse.bambaray.mg/backend/"
          only_newer: "true"
          ignore_time: "true"
          delete: "false"
          exclude: |
            .git*
            node_modules
            tests
            phpunit.xml
            README.md
            CHANGELOG.md
            .editorconfig
            .styleci.yml
            etn_database.sql
